backend:
<<<<<<< Updated upstream
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
=======
  name: github
  repo: krig-agency/krig.io
>>>>>>> Stashed changes

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

local_backend: true
publish_mode: editorial_workflow
